version: "1"

services:
  video-watchtime-nest:
    restart: always
    build:
      context: ./video-watchtime-nest
    volumes:
      - ./video-watchtime-nest:/app
      - ./video-watchtime-nest/node_modules:/app/node_modules
      - /app/node_modules/bcrypt/
    ports:
      - 3333:3333
    command: sh -c "yarn start:dev"
    #command: tail -F anything
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: localhost-websocket
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
